# Generated by Django 5.1 on 2024-08-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.JSONField(default=dict)),
                ('median', models.JSONField(default=dict)),
                ('mode', models.JSONField(default=dict)),
                ('uploaded_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='ingestion.uploadeddata')),
            ],
        ),
    ]
