# Generated by Django 5.1 on 2024-08-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_datastatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataStatistics',
        ),
    ]
